"""initial
Revision ID: 26108b642ff4
Revises: 
Create Date: 2023-03-28 12:53:28.504980
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26108b642ff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('subject', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('grades',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('teachers_id', sa.Integer(), nullable=True),
                    sa.Column('students_id', sa.Integer(), nullable=True),
                    sa.Column('grade', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['students_id'], ['students.id'], ),
                    sa.ForeignKeyConstraint(
                        ['teachers_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
